server:
    port: 8888

spring:
    datasource:
        driver: com.mysql.jdbc.cj.Driver
        url: jdbc:mysql://localhost:3306/business?useUnicode=true&characterEncoding=utf-8&serverTimezone=GMT%2B8
        username: root
        password: haitaotao123!

logging:
    file:
        path: log