server:
  port: 8888

spring:
  datasource:
    druid:
      first:
        url: jdbc:mysql://localhost:3306/business?useUnicode=true&characterEncoding=utf-8&serverTimezone=GMT%2B8
        username: root
        password: 123456
        driverClassName: com.mysql.cj.jdbc.Driver
      second:
        url: jdbc:mysql://localhost:3316/business?useUnicode=true&characterEncoding=utf-8&serverTimezone=GMT%2B8
        username: root
        driverClassName: com.mysql.cj.jdbc.Driver
      third:
        url: jdbc:mysql://localhost:3326/business?useUnicode=true&characterEncoding=utf-8&serverTimezone=GMT%2B8
        username: root
        driverClassName: com.mysql.cj.jdbc.Driver
